const quotes = [
    "Understand this well: there is something holy, something divine hidden in the most ordinary situations, and it is up to each one of you to discover it.--Josemaria Escriva",
    "Say the Holy Rosary. Blessed be that monotony of Hail Mary's which purifies the monotony of your sins!--Josemaria Escriva",
    "Don't judge without having heard both sides. Even persons who think themselves virtuous very easily forget this elementary rule of prudence.--Josemaria Escriva",
    "As soon as you willfully allow a dialogue with temptation to begin, the soul is robbed of peace, just as consent to impurity destroys grace.--Josemaria Escriva",
    "You always leave the Rosary for later, and you end up not saying it at all because you are sleepy. If there is no other time, say it in the street without letting anybody notice it. It will, moreover, help you to have presence of God.--Josemaria Escriva",
    "You're bored? That's because you keep your senses awake and your soul asleep.--Josemaria Escriva",
    "Compromise is a word found only in the vocabulary of those who have no will to fight.--Josemaria Escriva",
    "If I love, there will be no hell for me.--Josemaria Escriva",
    "Put your heart aside. Duty comes first. But when fulfilling your duty, put your heart into it. It helps.--Josemaria Escriva",
    "The holy Rosary is a powerful weapon. Use it with confidence and you'll be amazed at the results.--Josemaria Escriva",
    "If you have so many defects, why are you surprised to find defects in others?--Josemaria Escriva",
    "Love our Lady. And she will obtain abundant grace to help you conquer in your daily struggle.--Josemaria Escriva",
    "For those who use their intelligence and their study as a weapon, the Rosary is most effective. Because that apparently monotonous way of beseeching Our Lady as children do their Mother, can destroy every seed of vainglory and pride.--Josemaria Escriva",
    "When you decide firmly to lead a clean life, chastity will not be a burden on you: it will be a crown of triumph.--Josemaria Escriva",
    "Faith, joy, optimism. But not the folly of closing your eyes to reality.--Josemaria Escriva",
    "You strayed from the way and did not return because you were ashamed. It would be more logical if you were ashamed not to return.--Josemaria Escriva",
    "You don't know how to pray? Put yourself in the presence of God, and as soon as you have said, 'Lord, I don't know how to pray!\" you can be sure you have already begun.\"--Josemaria Escriva",
    "For everyone, whatever his state--single, married, widowed, or priest-chastity is a triumphant affirmation of love.--Josemaria Escriva",
    "It's true he was a sinner. But don't pass so final a judgement. Have pity in your heart and don't forget that he may yet be an Augustine, while you remain just another mediocrity.--Josemaria Escriva",
    "Christian optimism is not a sugary optimism, nor is it a mere human confidence that everything will turn out all right. It is an optimism that sinks its roots into an awareness of our freedom, and the sure knowledge of the power of grace. It is an optimism that leads us to make demands on ourselves, to struggle to respond at every moment to God's call.--Josemaria Escriva",
    "You need a heart which is in love, not an easy life, to achieve happiness.--Josemaria Escriva",
    "You can be sure you are a man of God if you suffer injustice gladly and in silence.--Josemaria Escriva",
    "At the time of your examination(of sins) beware of the devil that ties your tongue.--Josemaria Escriva",
    "'You told me, Father, that after my past life it is still possible to become another St. Augustine. I don't doubt it, and today more than yesterday I want to try to prove it.' But you have to cut out sin courageously from the root, as the holy Bishop of Hippo did.--Josemaria Escriva",
    "When you approach the tabernacle remember that he has been waiting for you for twenty centuries.--Josemaria Escriva",
    "You go to pray; to become a bonfire, a living flame, giving light and heat.--Josemaria Escriva",
    "Don't you long to shout to those youths who are bustling around you: Fools! Leave those worldly things that shackle the heart - and very often degrade it - leave all that and come with us in search of Love!--Josemaria Escriva",
    "God is here. This truth should fill our lives, and every Christmas should be for us a new and special meeting with God, when we allow his light and grace to enter deep into our soul.--Josemaria Escriva",
    "When we were little, we kept close to our mother in a dark alley or if dogs barked at us. Now, when we feel temptations of the flesh, we should run to the side of our Mother in Heaven, by realizing how she is to us, and by means of aspirations. She will defend us and lead us to the light.--Josemaria Escriva",
    "Have confidence. Return. Invoke our Lady and you'll be faithful.--Josemaria Escriva",
    "There is no danger of exaggerating. We an never hope to fathom this inexpressible mystery nor will we ever be able to give sufficient thanks to our Mother for bringing us into such intimacy with the Blessed Trinity.--Josemaria Escriva",
    "Before, by yourself, you couldn't. Now, you've turned to our Lady, and with her, how easy!--Josemaria Escriva",
    "All the sins of your life seem to be rising up against you. Don't give up hope! On the contrary, call your holy mother Mary, with the faith and abandonment of a child. She will bring peace to your soul.--Josemaria Escriva",
    "All the things that are now worrying you can be put into a smile which shows your love of God.--Josemaria Escriva",
    "May I give you some advice for you to put into practice daily? When your heart makes you feel those low cravings, say slowly to the Immaculate Virgin: Look on me with compassion. Don't abandon me. Don't abandon me, my Mother! - And recommend this prayer to others.--Josemaria Escriva",
    "You must realise now, more clearly than ever, that God is calling you to serve Him in and from the ordinary, secular and civil activities of human life. He waits for us everyday, in the laboratory, in the operating theatre, in the army barracks, in the university chair, in the factory, in the workshop, in the fileds, in the home and in all the immense panorama of work.--Josemaria Escriva",
    "We all must have the faith of children, but the doctrine of theologians.--Josemaria Escriva",
    "I assure you, my children, that when a Christian carries out with love the most insignificant everyday action, that action overflows with the transcendence of God. That is why I have told you so often, and hammered away at it, that the Christian vocation consists in making heroic verse out of the prose of each day. Heaven and earth seem to merge, my children, on the horizon. But where they really meet is in your hearts, when you sanctify your everyday lives...--Josemaria Escriva",
    "If you don't have a plan of life, you'll never have order.--Josemaria Escriva",
    "There is need for a crusade of manliness and purity to counteract and nullify the savage work of those who think man is a beast. And that crusade is your work.--Josemaria Escriva",
    "Many Christians take their time and have leisure enough in their social life (no hurry here). They are leisurely, too, in their professionally activities, at table and recreation (no hurry here either). But isn't it strange how those same Christians find themselves in such a rush and want to hurry the priest, in their anxiety to shorten the time devoted to the most holy sacrifice of the altar?--Josemaria Escriva",
    "When you see the storm coming, if you seek safety in that firm refuge which is Mary, there will be no danger of your wavering or going down.--Josemaria Escriva",
    "Temptation is necessary to make us realize that we are nothing in ourselves.--Josemaria Escriva",
    "Holy Purity is granted by God when it is asked for with humility.--Josemaria Escriva",
    "He has much who needs least. Do not create necessities for yourself.--Josemaria Escriva",
];
