const quotes = [
    "Understand this well: there is something holy, something divine hidden in the most ordinary situations, and it is up to each one of you to discover it. (Conversations, 114)",
    "Immaculate Virgin, I know well that I am only a miserable wretch, and all I do is increase each day the number of my sins… ” You told me the other day that was how you spoke to Our Mother. And I was confident in advising you with assurance to say the Holy Rosary. Blessed be that monotony of Hail Marys which purifies the monotony of your sins!(Furrow, 475)",
    "Don't judge without having heard both sides. Even persons who think themselves virtuous very easily forget this elementary rule of prudence. (The Way, 454)",
    "As soon as you willfully allow a dialogue with temptation to begin, the soul is robbed of peace, just as consent to impurity destroys grace. (Furrow, 836)",
    "You always leave the Rosary for later, and you end up not saying it at all because you are sleepy. If there is no other time, say it in the street without letting anybody notice it. It will, moreover, help you to have presence of God. (Furrow, 478)",
    "You're bored? That's because you keep your senses awake and your soul asleep. (The Way, 368)",
    "'One must compromise' Compromise is a word found only in the vocabulary of those who have no will to fight ﻿—﻿ the lazy, the cunning, the cowardly ﻿—﻿ for they consider themselves defeated before they start. (The Way, 54)",
    "If I love, there will be no hell for me. (The Forge, 1047)",
    "Put your heart aside. Duty comes first. But when fulfilling your duty, put your heart into it. It helps. (The Way, 162)",
    "The holy Rosary is a powerful weapon. Use it with confidence and you'll be amazed at the results. (The Way, 558)",
    "If you have so many defects, why are you surprised to find defects in others? (The Way, 446)",
    "Love our Lady. And she will obtain for you abundant grace to conquer in your daily struggle. And the enemy will gain nothing by those foul things that continually seem to boil and rise within you, trying to engulf in their fragrant corruption the high ideals, the sublime determination that Christ himself has set in your heart. ﻿—﻿ Serviam, I will serve! (The Way, 493)",
    "The Rosary is most effective for those who use their intelligence and their study as a weapon. Because that apparently monotonous way of beseeching Our Lady as children do their Mother, can destroy every seed of vainglory and pride. (Furrow, 474)",
    "When you resolve firmly to lead a clean life, chastity will not be a burden for you: it will be a triumphal crown. (The Way, 123)",
    "Faith, joy, optimism. But not the folly of closing your eyes to reality. (The Way, 40)",
    "You went astray, and did not come back because you were ashamed to. It would be more logical if you were ashamed not to return. (The Way, 985)",
    "You say that you don't know how to pray? Put yourself in the presence of God, and once you have said, 'Lord, I don't know how to pray!' rest assured that you have begun to do so. (The Way, 90)",
    "For everyone, whatever his state--single, married, widowed, or priest-chastity is a triumphant affirmation of love. (Furrow, 831)",
    "It's true that he was a sinner. But don't pass so final a judgment on him. Have pity in your heart, and don't forget that he may yet be an Augustine, while you remain just another mediocrity. (The Way, 675)",
    "Christian optimism is not a sugary optimism; nor is it a mere human confidence that everything will turn out all right. It is an optimism that sinks its roots in an awareness of our freedom, and in the sure knowledge of the power of grace. It is an optimism which leads us to make demands on ourselves, to struggle to respond at every moment to God’s calls. (The Forge, 659)",
    "You need a heart which is in love, not an easy life, to achieve happiness. (Furrow, 795)",
    "You can be sure you are a man of God if you suffer injustice gladly and in silence. (The Way, 672)",
    "At the time of your examination(of sins) beware of the devil that ties your tongue. (The Way, 236)",
    "“You told me, Father, that after my past life it is still possible to become another Saint Augustine. I don’t doubt it, and today more than yesterday I want to try to prove it.” But you have to cut out sin courageously from the root, as the holy Bishop of Hippo did. (Furrow, 838)",
    "When you approach the tabernacle remember that he has been waiting for you for twenty centuries. (The Way, 537)",
    "'Et in meditatione mea exardescit ignis. And in my meditation a fire shall flame out.' That is why you go to pray: to become a bonfire, a living flame giving heat and light. So, when you are not able to go on, when you feel that your fire is dying out, if you cannot throw on it sweet﻿—﻿ smelling logs, throw on the branches and twigs of short vocal prayers and ejaculations, to keep the bonfire burning. And you will not have wasted your time. (The Way, 92)",
    "Don't you long to shout to those young men and women all around you: Fools, leave those worldly things that shackle the heart and very often degrade it…, leave all that and come with us in search of Love? (The Way, 790)",
    "God is here. This truth should fill our lives... (Christ is Passing By, 12)",
    "When we were little, we kept close to our mother in a dark alley or if dogs barked at us. Now, when we feel temptations of the flesh, we should run to the side of Our Mother in Heaven, by realising how close she is to us, and by means of aspirations. —﻿She will defend us and lead us to the light. (Furrow, 847)",
    "Have confidence. Return. Invoke our Lady and you'll be faithful. (The Way, 514)",
    "Before, by yourself, you couldn't. Now, you have turned to our Lady, and, with her, how easy it is! (The Way, 513)",
    "All the sins of your life seem to rise up against you. Don't lose confidence. Rather, call on your holy Mother Mary, with the faith and abandonment of a child. She will bring peace to your soul.(The Way, 498)",
    "All the things that are now worrying you can be solved by making an effort to smile for love of God. (Furrow, 89)",
    "May I give you some advice for you to put into practice daily? When your heart makes you feel those low cravings, say slowly to the Immaculate Virgin: Look on me with compassion. Don’t abandon me, my Mother! ﻿—﻿And recommend this prayer to others.(Furrow, 849)",
    "We all must have the faith of children, but the doctrine of theologians. (Christ is passing by, 10)",
    "If you don't have a plan of life, you'll never have order. (The Way, 76)",
    "There is need for a crusade of manliness and purity to counteract and undo the savage work of those who think that man is a beast. And that crusade is a matter for you. (The Way, 121)",
    "Isn't it strange how many Christians, who take their time and have leisure enough in their social life (they are in no hurry), in following the sleepy rhythm of their professional affairs, in eating and recreation (no hurry here either), find themselves rushed and want to rush the Priest, in their anxiety to shorten the time devoted to the most holy Sacrifice of the Altar? (The Way, 530)",
    "Sancta Maria, Stella maris ﻿—﻿ Holy Mary, Star of the sea, be our guide. Make this firm request, because there is no storm which can shipwreck the most Sweet Heart of Mary. When you see the storm coming, if you get into that firm Refuge which is Mary, there will be no danger of your wavering or going down. (The Forge, 1055)",
    "Looking at my life, I see quite honestly that I myself am nothing, am worth nothing and have nothing, that I can do nothing and, even more, that I am nothingness itself! But He is everything and, at the same time, he belongs to me and I to him because he does not reject me and has given himself up for me. Have you ever seen a greater love than this? (Friends of God, 215)",
    "Holy Purity is granted by God when it is asked for with humility. (The Way, 118)",
    "He has much who needs least. Do not create necessities for yourself. (The Way, 630)",
];
